"""Initial Migration

Revision ID: 57991eb90bc2
Revises: 
Create Date: 2021-03-01 11:16:59.152091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57991eb90bc2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=64), nullable=True))
    op.drop_index('ix_users_name', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=64), nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_name', 'users', ['name'], unique=1)
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
